# Generated by Django 4.2.5 on 2023-09-29 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='pills',
            name='isLottie',
            field=models.BooleanField(default=True, verbose_name='Lottie?'),
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Telefone')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contacts')),
            ],
        ),
    ]
