# Generated by Django 4.2.5 on 2023-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacts_alter_pills_islottie_phones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name': 'Número', 'verbose_name_plural': 'Números'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
