# Generated by Django 4.2.5 on 2023-10-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='information',
            name='themeColor',
            field=models.CharField(blank=True, null=True, verbose_name='cor'),
        ),
    ]
