# Generated by Django 4.2.5 on 2023-10-02 22:42

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_information_img_alter_information_themecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='img',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, null=True, pixel_densities=[1, 2], upload_to='img/', verbose_name='imagem'),
        ),
    ]
