# Generated by Django 3.2.22 on 2023-10-11 00:35

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_information_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='img/', variations={}, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='information',
            name='themeColor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='cor'),
        ),
    ]
